test wheel build

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,146 +1,157 @@
 name: Release
 
 on:
-  workflow_dispatch
+  workflow_dispatch:
+    inputs:
+      build_wheel:
+        description: "Build wheels"
+        required: true
+        default: true
+        type: boolean
+      publish_package:
+        description: "Publish package"
+        required: true
+        default: true
+        type: boolean
 
-jobs:
-  generate_videos:
-    name: Generate videos for ${{ matrix.target }}
-    runs-on: [self-hosted, multigpu]
-    strategy:
-      matrix:
-        target: [ltx]
-        include:
-          - target: ltx
-            repo_url: test-org-139/LTX-Video.git # TODO: change to moonmath-ai
-            repo_name: LTX-Video
-            branch: ci-lite-attention
-            prompts_branch: ltx-short
-            prompts_repo: test-org-139/ci-prompts-list.git # TODO: change to moonmath-ai
+# jobs:
+#   generate_videos:
+#     name: Generate videos for ${{ matrix.target }}
+#     runs-on: [self-hosted, multigpu]
+#     strategy:
+#       matrix:
+#         target: [ltx]
+#         include:
+#           - target: ltx
+#             repo_url: test-org-139/LTX-Video.git # TODO: change to moonmath-ai
+#             repo_name: LTX-Video
+#             branch: ci-lite-attention
+#             prompts_branch: ltx-short
+#             prompts_repo: test-org-139/ci-prompts-list.git # TODO: change to moonmath-ai
     
-    steps:
-      - name: Create GitHub App token
-        id: app-token
-        uses: actions/create-github-app-token@v2
-        with:
-          app-id: ${{ secrets.CI_PULL_ID }}
-          private-key: ${{ secrets.CI_PULL_SECRET }}
-          owner: test-org-139 # TODO: change to moonmath-ai
+#     steps:
+#       - name: Create GitHub App token
+#         id: app-token
+#         uses: actions/create-github-app-token@v2
+#         with:
+#           app-id: ${{ secrets.CI_PULL_ID }}
+#           private-key: ${{ secrets.CI_PULL_SECRET }}
+#           owner: test-org-139 # TODO: change to moonmath-ai
 
-      - name: Checkout LiteAttention Repository
-        uses: actions/checkout@v4
-        with:
-          path: LiteAttention
+#       - name: Checkout LiteAttention Repository
+#         uses: actions/checkout@v4
+#         with:
+#           path: LiteAttention
       
-      - name: Checkout ${{ matrix.target }} Repository
-        uses: actions/checkout@v4
-        with:
-          repository: ${{ matrix.repo_url }}
-          ref: ${{ matrix.branch || 'main' }}
-          path: ${{ matrix.repo_name }}
-          submodules: 'recursive'
-          lfs: true
-          fetch-depth: 0
-          token: ${{ steps.app-token.outputs.token }}
-          persist-credentials: false
+#       - name: Checkout ${{ matrix.target }} Repository
+#         uses: actions/checkout@v4
+#         with:
+#           repository: ${{ matrix.repo_url }}
+#           ref: ${{ matrix.branch || 'main' }}
+#           path: ${{ matrix.repo_name }}
+#           submodules: 'recursive'
+#           lfs: true
+#           fetch-depth: 0
+#           token: ${{ steps.app-token.outputs.token }}
+#           persist-credentials: false
       
-      - name: Checkout prompts list
-        uses: actions/checkout@v4
-        with:
-          path: ${{ matrix.repo_name }}-prompts
-          repository: ${{ matrix.prompts_repo }}
-          ref: ${{ matrix.prompts_branch }}
-          lfs: true
-          token: ${{ steps.app-token.outputs.token }}
-          persist-credentials: false
+#       - name: Checkout prompts list
+#         uses: actions/checkout@v4
+#         with:
+#           path: ${{ matrix.repo_name }}-prompts
+#           repository: ${{ matrix.prompts_repo }}
+#           ref: ${{ matrix.prompts_branch }}
+#           lfs: true
+#           token: ${{ steps.app-token.outputs.token }}
+#           persist-credentials: false
 
-      - name: temp step
-        working-directory: ${{ matrix.repo_name }}
-        run: |
-          INPUT_PATH=$(pwd)/../${{ matrix.repo_name }}-prompts
-          OUTPUT_PATH=$HOME/output/${{ matrix.target }}-${{github.sha}}
-          CACHE_DIR=$HOME/.cache/
-          echo "INPUT_PATH=$(pwd)/../${{ matrix.repo_name }}-prompts" >> $GITHUB_ENV
-          echo "OUTPUT_PATH=$HOME/output/${{ matrix.target }}-${{github.sha}}" >> $GITHUB_ENV
-          echo "CACHE_DIR=$HOME/.cache/" >> $GITHUB_ENV
-          mkdir -p $HOME/output/
-          mkdir -p $OUTPUT_PATH
-          mkdir -p $CACHE_DIR
-          cp $INPUT_PATH/ref_videos/* $OUTPUT_PATH/
+#       - name: temp step
+#         working-directory: ${{ matrix.repo_name }}
+#         run: |
+#           INPUT_PATH=$(pwd)/../${{ matrix.repo_name }}-prompts
+#           OUTPUT_PATH=$HOME/output/${{ matrix.target }}-${{github.sha}}
+#           CACHE_DIR=$HOME/.cache/
+#           echo "INPUT_PATH=$(pwd)/../${{ matrix.repo_name }}-prompts" >> $GITHUB_ENV
+#           echo "OUTPUT_PATH=$HOME/output/${{ matrix.target }}-${{github.sha}}" >> $GITHUB_ENV
+#           echo "CACHE_DIR=$HOME/.cache/" >> $GITHUB_ENV
+#           mkdir -p $HOME/output/
+#           mkdir -p $OUTPUT_PATH
+#           mkdir -p $CACHE_DIR
+#           cp $INPUT_PATH/ref_videos/* $OUTPUT_PATH/
       
-      # - name: Build Docker image
-      #   working-directory: ${{ matrix.repo_name }}
-      #   run: |
-      #     docker build --build-context lite=$(pwd)/../LiteAttention -t ${{ matrix.target }}:${{github.sha}} .
+#       # - name: Build Docker image
+#       #   working-directory: ${{ matrix.repo_name }}
+#       #   run: |
+#       #     docker build --build-context lite=$(pwd)/../LiteAttention -t ${{ matrix.target }}:${{github.sha}} .
       
-      # - name: Run Video Generation in Docker container
-      #   working-directory: ${{ matrix.repo_name }}
-      #   run: |
-      #     INPUT_PATH=$(pwd)/../${{ matrix.repo_name }}-prompts
-      #     OUTPUT_PATH=$HOME/output/${{ matrix.target }}-${{github.sha}}
-      #     CACHE_DIR=$HOME/.cache/
-      #     echo "INPUT_PATH=$INPUT_PATH" >> $GITHUB_ENV
-      #     echo "OUTPUT_PATH=$OUTPUT_PATH" >> $GITHUB_ENV
-      #     echo "CACHE_DIR=$CACHE_DIR" >> $GITHUB_ENV
-      #     mkdir -p $HOME/output/
-      #     mkdir -p $OUTPUT_PATH
-      #     mkdir -p $CACHE_DIR
+#       # - name: Run Video Generation in Docker container
+#       #   working-directory: ${{ matrix.repo_name }}
+#       #   run: |
+#       #     INPUT_PATH=$(pwd)/../${{ matrix.repo_name }}-prompts
+#       #     OUTPUT_PATH=$HOME/output/${{ matrix.target }}-${{github.sha}}
+#       #     CACHE_DIR=$HOME/.cache/
+#       #     echo "INPUT_PATH=$INPUT_PATH" >> $GITHUB_ENV
+#       #     echo "OUTPUT_PATH=$OUTPUT_PATH" >> $GITHUB_ENV
+#       #     echo "CACHE_DIR=$CACHE_DIR" >> $GITHUB_ENV
+#       #     mkdir -p $HOME/output/
+#       #     mkdir -p $OUTPUT_PATH
+#       #     mkdir -p $CACHE_DIR
           
-      #     docker run --rm --gpus all \
-      #       -v $INPUT_PATH:/input \
-      #       -v $OUTPUT_PATH:/output \
-      #       -v $CACHE_DIR:/root/.cache \
-      #       ${{ matrix.target }}:${{github.sha }} \
-      #       python3 inference_ci.py \
-      #         --input_file /input/prompts.jsonl \
-      #         --output_path /output \
-      #         --videos_per_prompt ${{ vars.VIDEOS_PER_PROMPT || 1 }}
+#       #     docker run --rm --gpus all \
+#       #       -v $INPUT_PATH:/input \
+#       #       -v $OUTPUT_PATH:/output \
+#       #       -v $CACHE_DIR:/root/.cache \
+#       #       ${{ matrix.target }}:${{github.sha }} \
+#       #       python3 inference_ci.py \
+#       #         --input_file /input/prompts.jsonl \
+#       #         --output_path /output \
+#       #         --videos_per_prompt ${{ vars.VIDEOS_PER_PROMPT || 1 }}
       
-      - name: Checkout surveyor2 repository
-        uses: actions/checkout@v4
-        with:
-          repository: test-org-139/surveyor2.git # TODO: change to moonmath-ai
-          ref: main
-          path: surveyor2
-          token: ${{ steps.app-token.outputs.token }}
-          persist-credentials: false
+#       - name: Checkout surveyor2 repository
+#         uses: actions/checkout@v4
+#         with:
+#           repository: test-org-139/surveyor2.git # TODO: change to moonmath-ai
+#           ref: main
+#           path: surveyor2
+#           token: ${{ steps.app-token.outputs.token }}
+#           persist-credentials: false
       
-      - name: Build surveyor2 Docker image
-        working-directory: surveyor2
-        run: |
-          docker build -t surveyor2:${{github.sha}} .
+#       - name: Build surveyor2 Docker image
+#         working-directory: surveyor2
+#         run: |
+#           docker build -t surveyor2:${{github.sha}} .
       
-      - name: Run Surveyor2 in Docker container
-        run: |
-          docker run --rm --gpus all \
-            -v ${{ env.INPUT_PATH }}:/input \
-            -v ${{ env.OUTPUT_PATH }}:/generated_videos \
-            -v ${{ env.CACHE_DIR }}:/root/.cache \
-            surveyor2:${{github.sha }} \
-            /bin/bash -lc "
-            surveyor2 inputs \
-              --prompts /input/prompts.jsonl \
-              --reference-videos /input/ref_videos \
-              --generated-videos /generated_videos \
-              --output inputs.yaml && \
-            surveyor2 profile \
-              --inputs inputs.yaml \
-              --report-json /generated_videos/report.json && \
-            surveyor2 markdown \
-              --input /generated_videos/report.json \
-              --output /generated_videos/report.md"
-      - name: Upload generated videos
-        uses: actions/upload-artifact@v4
-        with:
-          name: "${{ matrix.target }}-videos-${{ github.sha }}"
-          path: ${{ env.OUTPUT_PATH }}
-          retention-days: 30
+#       - name: Run Surveyor2 in Docker container
+#         run: |
+#           docker run --rm --gpus all \
+#             -v ${{ env.INPUT_PATH }}:/input \
+#             -v ${{ env.OUTPUT_PATH }}:/generated_videos \
+#             -v ${{ env.CACHE_DIR }}:/root/.cache \
+#             surveyor2:${{github.sha }} \
+#             /bin/bash -lc "
+#             surveyor2 inputs \
+#               --prompts /input/prompts.jsonl \
+#               --reference-videos /input/ref_videos \
+#               --generated-videos /generated_videos \
+#               --output inputs.yaml && \
+#             surveyor2 profile \
+#               --inputs inputs.yaml \
+#               --report-json /generated_videos/report.json && \
+#             surveyor2 markdown \
+#               --input /generated_videos/report.json \
+#               --output /generated_videos/report.md"
+#       - name: Upload generated videos
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: "${{ matrix.target }}-videos-${{ github.sha }}"
+#           path: ${{ env.OUTPUT_PATH }}
+#           retention-days: 30
       
-      - name: Cleanup Docker images
-        if: always()
-        run: |
-          docker rmi ${{ matrix.target }}:${{ github.sha }} || true
-          docker rmi surveyor2:${{ github.sha }} || true
+#       - name: Cleanup Docker images
+#         if: always()
+#         run: |
+#           docker rmi ${{ matrix.target }}:${{ github.sha }} || true
+#           docker rmi surveyor2:${{ github.sha }} || true
 
   create_draft_release:
     name: Create Draft Release with Videos
@@ -175,6 +186,7 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           LATEST_TAG=$(git describe --tags --abbrev=0)
+          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
           gh release create $LATEST_TAG --generate-notes -d --verify-tag -t "Release $LATEST_TAG"
       
       - name: Upload example_videos archive to Release
@@ -182,6 +194,73 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           LATEST_TAG=$(git describe --tags --abbrev=0)
-          gh release upload $LATEST_TAG example_videos.tar.gz
+          gh release upload ${{ env.LATEST_TAG }} example_videos.tar.gz
 
+  build_wheels:
+    name: Build Wheel
+    needs: create_draft_release
+    if: ${{ inputs.build_wheels }}
+    strategy:
+      fail-fast: false
+      matrix:
+        # Using ubuntu-22.04 instead of 24.04 for more compatibility (glibc). Ideally we'd use the
+        # manylinux docker image, but I haven't figured out how to install CUDA on manylinux.
+        # os: [ubuntu-22.04, ubuntu-22.04-arm]
+        docker-image: [ubuntu:22.04]
+        python-version: ["3.10", "3.11", "3.12", "3.13"]
+        torch-version: ["2.5.1", "2.6.0", "2.7.1", "2.8.0", "2.9.1"]
+        cuda-version: ["12.9.1"]
+        # We need separate wheels that either uses C++11 ABI (-D_GLIBCXX_USE_CXX11_ABI) or not.
+        # Pytorch wheels currently don't use it, but nvcr images have Pytorch compiled with C++11 ABI.
+        # Without this we get import error (undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs)
+        # when building without C++11 ABI and using it on nvcr images.
+        cxx11_abi: ["FALSE", "TRUE"]
+        include:
+            - torch-version: "2.9.1"
+              cuda-version: "13.0.2"
+              python-version: "3.14" 
+            - torch-version: "2.10.0.dev20251108"
+              cuda-version: "13.0.2"
+        exclude:
+          # see https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix
+          # Pytorch < 2.5 does not support Python 3.13
+          - torch-version: "2.4.0"
+            python-version: "3.13"
+    uses: ./.github/workflows/_build.yml
+    with:
+      docker-image: ${{ matrix.docker-image }}
+      python-version: ${{ matrix.python-version }}
+      cuda-version: ${{ matrix.cuda-version }}
+      torch-version: ${{ matrix.torch-version }}
+      cxx11_abi: ${{ matrix.cxx11_abi }}
+      release-version: ${{ env.LATEST_TAG }}
+      upload-to-release: true
 
+  publish_package:
+    name: Publish package
+    needs: [build_wheels]
+    if: ${{ inputs.publish_package }}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+      - uses: actions/setup-python@v6
+        with:
+          python-version: "3.10"
+      - name: Install dependencies
+        run: |
+          pip install ninja packaging wheel twine
+          # Install latest setuptools with support for pypi metadata 2.2 (improved compat w/ uv)
+          pip install setuptools==75.8.0
+          # We don't want to download anything CUDA-related here
+          pip install torch --index-url https://download.pytorch.org/whl/cpu
+      - name: Build core package
+        env:
+          FLASH_ATTENTION_SKIP_CUDA_BUILD: "TRUE"
+        run: |
+          python setup.py sdist --dist-dir=dist
+      - name: Deploy
+        env:
+          TWINE_USERNAME: "__token__"
+          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
+        run: |
+          python -m twine upload dist/*
